version: '3'
services:
    xana:
        build: ./app
        ports:
            - "4000:4000"
        depends_on:
            - postgres
    postgres:
        image: postgres
        volumes:
           - postgres:/data/postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: toor
        ports:
          - "5432:5432"
        restart: on-failure

volumes:
    postgres: {}