version: '3'
services:
    isis:
        build: ./app
        ports:
            - "4000:4000"
        depends_on:
            - redis
            - mysql
    redis:
        image: redis
        ports:
            - "5372:5372"
    mysql:
        image: mysql:5.7
        ports:
            - "7392:7392"
        environment:
            MYSQL_ROOT_PASSWORD: toor