version: "3"
services:
  xana:
    build: ./app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file: xana.env
  postgres:
    image: postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sites.csv:/app/sites.csv
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    restart: always
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  postgres: {}
